CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE statusinvest
(
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  name character varying(255) NOT NULL,
  sector character varying(255),
  sub_sector character varying(255),
  segment character varying(255),
  value numeric(20,2),
  variation_last_12_month numeric(20,2),
  min_in_last_12_month numeric(20,2),
  max_in_last_12_month numeric(20,2),
  payment_last_12_month numeric(20,2),
  dividend_yield numeric(20,2),
  variation_in_month numeric(20,2),
  min_in_month numeric(20,2),
  max_in_month numeric(20,2),
  appreciation_in_month numeric(20,2),
  pvp numeric(20,2),
  pl numeric(20,2),
  pebitda numeric(20,2),
  pebit numeric(20,2),
  pativo numeric(20,2),
  evebitda numeric(20,2),
  evebit numeric(20,2),
  psr numeric(20,2),
  p_working_capital numeric(20,2),
  p_current_assets_net numeric(20,2),
  gross_margin numeric(20,2),
  ebitda_margin numeric(20,2),
  ebit_margin numeric(20,2),
  net_margin numeric(20,2),
  turn_asset numeric(20,2),
  roe numeric(20,2),
  roa numeric(20,2),
  roic numeric(20,2),
  lpa numeric(20,2),
  vpa numeric(20,2),
  net_debt_patrimony numeric(20,2),
  net_debt_ebitda numeric(20,2),
  net_debt_ebit numeric(20,2),
  patrimony_assets numeric(20,2),
  liabilities_assets numeric(20,2),
  current_liquidity numeric(20,2),
  cagr_revenue numeric(20,2),
  cagr_profit numeric(20,2),
  crawled_at timestamp NOT NULL,
  CONSTRAINT statusinvest_pkey PRIMARY KEY (id)
);